frontend/controllers/UsersController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use frontend\models\UserUpdateForm;

class UsersController extends Controller
{
	public function actionSettings()
	{
		if (Yii::$app->user->isGuest)
		{
			return $this->goHome();
		}

		$model = new UserUpdateForm();
		$user = Yii::$app->user->identity;

		if ($model->load(Yii::$app->request->post()) && $model->update($user))
		{
			$model->password = "";
			$model->password_retype = "";

			Yii::$app->session->setFlash("settings_update_success", "Settings updated successfully.");
		}
		else
		{
			$model->first_name = $user->first_name;
			$model->last_name = $user->last_name;
		}

		return $this->render("settings", [
			"model" => $model,
		]);
	}
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
	<?php
	NavBar::begin([
		"brandLabel" => Yii::$app->name,
		"brandUrl" => Yii::$app->homeUrl,
		"options" => [
			"class" => "navbar-inverse navbar-fixed-top",
		],
	]);
	$menuItems = [];
	if (Yii::$app->user->isGuest) {
		$menuItems[] = ["label" => "Signup", "url" => ["/site/signup"]];
		$menuItems[] = ["label" => "Login", "url" => ["/site/login"]];
	} else {
		$menuItems[] = ["label" => "Saved Tweets", "url" => "/tweets"];
		$menuItems[] = ["label" => "Settings", "url" => "/users/settings"];
		$menuItems[] = "<li>"
			. Html::beginForm(["/site/logout"], "post")
			. Html::submitButton(
				"Logout (" . Yii::$app->user->identity->username . ")",
				["class" => "btn btn-link logout"]
			)
			. Html::endForm()
			. "</li>";
	}
	echo Nav::widget([
		"options" => ["class" => "navbar-nav navbar-right"],
		"items" => $menuItems,
	]);
	NavBar::end();
	?>

	<div class="container">
		<?= Alert::widget() ?>
		<?= $content ?>
	</div>
</div>

<footer class="footer">
	<div class="container">
		<p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date("Y") ?></p>

		<p class="pull-right">Powered by <a target="_blank" href="http://instructit.com">Instrictit</a></p>
	</div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>